### ISSUE TITLE
Does it theoretically work on centos7?

### ISSUE THREAD

**Issue by unlackingc** [heterodb/nvme-strom#11]
Hi:
   I'm a student from china and intend to use this awesome project in my project(which try to accelerate the encoding process of erasure codes).
  As in README you said RHEL 7.3 has been tested. So is this means that **if the kernel is the same, then this project theoretically work on other OS like centos or even ubuntu**? Or the OS is strictly limited ?

**Comment by kaigai** [comment]
It will work on CentOS 7.3 also. I'm not certain about Ubuntu kernel (not tested yet, give me time!)

**Comment by unlackingc** [comment]
Thanks~ It very helpful.
As RHEL is not free.
